version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: complot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/complot
      - SECRET_KEY=change_me
    ports:
      - "8000:10000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:5000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000