services:
  - type: web
    name: complot-backend
    env: python
    instanceType: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
      - key: SECRET_KEY
    healthCheckPath: /health
  - type: static
    name: complot-frontend
    env: static
    buildCommand: yarn --cwd frontend install && yarn --cwd frontend build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL